#include "../HLSL/Mathx.hlsl"

uniform uint _ThreadCount;
uniform uint2 _Dimension;

globallycoherent RWStructuredBuffer<uint> gb_WaterHeight;
StructuredBuffer<float2> gb_WaterCoords;

#pragma kernel CalculateWaterHeight
[numthreads(64, 1, 1)]
void CalculateWaterHeight(uint DTid : SV_DispatchThreadID)
{
    if (DTid >= _ThreadCount) return;

    uint2 coord = uint2(gb_WaterCoords[DTid]);
    InterlockedAdd(gb_WaterHeight[flatten_uint2(coord, _Dimension)], 1);
}
